name: auto-merge

on:
  workflow_call:
    secrets:
      AUTOMATION_TOKEN:
        required: true

  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: aut-merge
        name: auto-merge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMATION_TOKEN }}"  
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_DELETE_BRANCH: "true"
          MERGE_ERROR_FAIL: "true"