name: auto-merge

on:
  workflow_call:
    secrets:
      AUTOMATION_TOKEN:
        required: true

  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-approve:
    name: auto-approve prs by boldlinksig
    runs-on: ubuntu-latest
    steps:
      - name: auto-approve
        uses: hmarr/auto-approve-action@v3
        if: github.actor == 'ndegwajohn'
        with:
          github-token: "${{ secrets.AUTOMATION_TOKEN }}" 
  auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    steps:
      - id: auto-merge
        name: auto-merge
        uses: "pascalgn/automerge-action@v0.15.5"
        if: github.actor == 'ndegwajohn'
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMATION_TOKEN }}"  
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_DELETE_BRANCH: "true"
          MERGE_ERROR_FAIL: "true"
