name: auto-merge

on:
  workflow_call:
    secrets:
      AUTOMATION_TOKEN:
        required: true
      SLACK_WEBHOOK:
        required: true

jobs:
  auto-approve:
    name: auto-approve prs by boldlinksig
    runs-on: ubuntu-latest
    steps:
      - name: auto-approve
        uses: hmarr/auto-approve-action@v3
        if: github.actor == 'boldlinksig'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}" 
      - name: Slack Notification failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Boldlinksig
          SLACK_MESSAGE: ":bell: Job failed."
          SLACK_FOOTER: "Bodlink-SIG 2022"
          SLACK_COLOR: ${{ job.status }} 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  
  auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    steps:
      - id: auto-merge
        name: auto-merge
        uses: "pascalgn/automerge-action@v0.15.5"
        if: github.actor == 'boldlinksig'
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMATION_TOKEN }}"  
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
          MERGE_ERROR_FAIL: "true"
      - name: Slack Notification failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Boldlinksig
          SLACK_MESSAGE: ":bell: Job failed."
          SLACK_FOOTER: "Bodlink-SIG 2022"
          SLACK_COLOR: ${{ job.status }} 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
