name: PR Labeler

on:
  workflow_call:
    inputs:
      configuration-path:
        required: true
        type: string

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: ${{inputs.configuration-path}}            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Boldlinksig
          SLACK_MESSAGE: ":bell: Job failed."
          SLACK_FOOTER: "Bodlink-SIG 2022"
          SLACK_COLOR: ${{ job.status }} 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
